### ISSUE TITLE
Use the Open Fact Verifier mech to resolve markets 

### ISSUE THREAD

**Issue by evangriffiths** [valory-xyz/market-creator#114]
See https://github.com/valory-xyz/mech/tree/main/packages/gnosis/customs/ofv_market_resolver

Some analysis done by the Gnosis AI team found the current resolver gets ~70% accuracy vs ~90% accuracy for this new mech. More detail in the PR description here https://github.com/valory-xyz/mech/pull/225

**Comment by jmoreira-valory** [comment]
This has already been implemented in the production deployment, by appropriately setting the variable `MECH_TOOL_RESOLVE_MARKET`. See an example here:

https://presagio.pages.dev/markets?id=0x8ed63a993f8a5f2dffa9b7098fc533bef35cd80b

https://gateway.autonolas.tech/ipfs/f01701220fe08629a3f0336f35d1ecb8ef2756db2e1a51b84d2070be6b4c3fb2aad25c78f/metadata.json

https://gateway.autonolas.tech/ipfs/f017012205a92ddcd439c33fbd72a764de7486be20efa888029deeaf8e36a32f49b4fc337/112427421698103880320058983485384268379982343228221862367707900789791222038676
